name: VPC Setup

on:
  workflow_dispatch:
  push:

jobs:
    setup_vpc:
        runs-on: ubuntu-24.04
        steps:
            - run: echo "setup vpc now"
            - run: |
                ls ${{github.workspace}}
                echo ${{github.event_name}}
                echo ${{github.repository}}
                echo "env details"
                echo env

